### ISSUE TITLE
503 from superagent

### ISSUE THREAD

**Issue by Tiliavir** [center-key/w3c-html-validator#2]
First of, thanks for the amazing library! I am validating my websites for years and this library is by far the most convenient way :-)

Unfortunately I get following error after updating to v1.0.0:

```bash
$ npx w3c-html-validator ./public/index.html 
/home/user/repo/node_modules/superagent/lib/node/index.js:904
        error = new Error(message);
                ^

<ref *4> Error: Service Unavailable
    at Request.callback (/home/user/repo/node_modules/superagent/lib/node/index.js:904:17)
    at IncomingMessage.<anonymous> (/home/user/repo/node_modules/superagent/lib/node/index.js:1148:20)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  status: 503,
  response: <ref *5> Response {
// ...
    serverError: true,
    error: Error: cannot POST /nu/?out=json (503)
        at Response.toError (/home/user/repo/node_modules/superagent/lib/node/response.js:98:15)
        at ResponseBase._setStatusProperties (/home/user/repo/node_modules/superagent/lib/response-base.js:119:48)
        at new Response (/home/user/repo/node_modules/superagent/lib/node/response.js:44:8)
        at Request._emitResponse (/home/user/repo/node_modules/superagent/lib/node/index.js:951:18)
        at IncomingMessage.<anonymous> (/home/user/repo/node_modules/superagent/lib/node/index.js:1148:42)
        at IncomingMessage.emit (node:events:402:35)
        at endReadableNT (node:internal/streams/readable:1343:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      status: 503,
      text: '<html><body><h1>503 Service Unavailable</h1>\n' +
        'No server is available to handle this request.\n' +
        '</body></html>\n',
      method: 'POST',
// ...
```

Not sure about the cause yet, but it looks reproducible. Am I missing something after updating to V1.0.0 or is it a problem with the w3c service being called?

Thanks and have a nice weekend
Markus

_Update: looks like a temporary issue with the service being called._

**Comment by Tiliavir** [comment]
Works like a charm again :-)

**Comment by pilafmon** [comment]
Gracefully handle **503 service unavailable** to output error like:
![503 SERVICE UNAVAILABLE](https://user-images.githubusercontent.com/119555/150945072-cd710b49-0f29-4755-822d-922ac08ec938.png)
