### ISSUE TITLE
Getting an error when trying to use this package in applicaton code

### ISSUE THREAD

**Issue by reinvanimschoot** [center-key/w3c-html-validator#5]
I'm using the package like so:

```ts
  import { w3cHtmlValidator } from 'w3c-html-validator';

  const html = ReactDOMServer.renderToStaticMarkup(elementWithCollectedStyles);

  const htmlDoc =
    `<!DOCTYPE html>
      <body>` +
    html +
    `</body>
    </html>`;

  const result = await w3cHtmlValidator.validate({
    html: htmlDoc,
  });
```
which results in the following error:

```
/Users/rein/workspace/brightbook-2/node_modules/pirates/lib/index.js:141
      oldLoader(mod, filename);
      ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/rein/workspace/brightbook-2/node_modules/w3c-html-validator/node_modules/chalk/source/index.js from /Users/rein/workspace/brightbook-2/node_modules/w3c-html-validator/dist/w3c-html-validator.umd.cjs not supported.
Instead change the require of index.js in /Users/rein/workspace/brightbook-2/node_modules/w3c-html-validator/dist/w3c-html-validator.umd.cjs to a dynamic import() which is available in all CommonJS modules.
    at newLoader (/Users/rein/workspace/brightbook-2/node_modules/pirates/lib/index.js:141:7)
    at require.extensions.<computed> [as .js] (/Users/rein/workspace/brightbook-2/node_modules/ts-node/dist/index.js:851:20)
    at /Users/rein/workspace/brightbook-2/node_modules/w3c-html-validator/dist/w3c-html-validator.umd.cjs:18:37
    at /Users/rein/workspace/brightbook-2/node_modules/w3c-html-validator/dist/w3c-html-validator.umd.cjs:8:17
    at Object.<anonymous> (/Users/rein/workspace/brightbook-2/node_modules/w3c-html-validator/dist/w3c-html-validator.umd.cjs:14:3)
    at Module._compile (/Users/rein/workspace/brightbook-2/node_modules/pirates/lib/index.js:136:24)
    at newLoader (/Users/rein/workspace/brightbook-2/node_modules/pirates/lib/index.js:141:7)
    at require.extensions.<computed> [as .cjs] (/Users/rein/workspace/brightbook-2/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/rein/workspace/brightbook-2/app/javascript/scripts/print-cli/renderHtml.tsx:33:30)
    at m._compile (/Users/rein/workspace/brightbook-2/node_modules/ts-node/dist/index.js:857:29)
    at newLoader (/Users/rein/workspace/brightbook-2/node_modules/pirates/lib/index.js:141:7)
    at require.extensions.<computed> [as .tsx] (/Users/rein/workspace/brightbook-2/node_modules/ts-node/dist/index.js:859:16) {
  code: 'ERR_REQUIRE_ESM'
}
```

Any help would be greatly appreciated.

**Comment by pilafmon** [comment]
Is it practical to upgrade your project to 100% ES modules?

`w3c-html-validator` includes distribution files for both **ES modules** and **CommonJS:**

**package.json**
```json
   "exports": {
      ".": {
         "import": "./dist/w3c-html-validator.js",
         "require": "./dist/w3c-html-validator.umd.cjs"
      },
      "./": "./dist/"
   },
```

However, it looks like one of the dependencies does not support **CommonJS** anymore.  At this point, **CommonJS** is so old and obsolete that it would be weird to spend time on it.  If anyone puts up a pull request to fix CommonJS support, I'll merge it.  Otherwise, it probably makes sense to drop support to avoid confusion.
